NEAR-DevHub/neardevhub-bos

- src/Post.jsx
In general, we need to add proper keys to all react-generated lists.
> fix: Render only one footer per post

- src/Ideas.metadata.json
- src/KanbanBoardList.jsx
- src/Post.jsx
I just discovered that VM really does not like rendering emptry string or null in place of an html element. So when I need to do conditional rendering and not render in some case I need to return `(<div></div>)` instead of `null` or `""`.
If you do it VM will create weird hard to debug rendering bugs.
> fix: React conditional rendering bug.

- .github/workflows/release.yml
CD works blazingly fast (just 5 seconds for the whole pipeline!), but fails due to the https://github.com/FroVolod/near-social/issues/8, I will leave this PR in draft.
> ci: Speed up near-social installation using binary release

- .github/workflows/release.yml
This fixes the error caught with the deployment of the `Ideas.metadata.json` (after #25) which has `null` value set to `app` tag (we want to remove that tag).
> ci: Bumped near-social CLI to 0.2.3

- src/gigs-board/components/posts/List.jsx
This new Posts List widget implementation was forked from [IndexFeed], but it does not fully implement lazy loading. While this component uses InfiniteScroll, it still loads the whole list of Post IDs in one view call. The contract will need to be extended with pagination support, yet, even in the current state the page loads much faster.
I left some of the original [IndexFeed] widget implementation in commented code for future PRs.
[IndexFeed]: https://near.social/#/mob.near/widget/WidgetSource?src=mob.near/widget/IndexFeed
Here is the link for testing: https://near.social/#/frol.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
> feat: Use InfiniteScroll to load the posts lazily

- src/gigs-board/components/posts/Post.jsx
Resolves #23.
Note, this only changes how tagged accounts are displayed, but it does not notify tagged people (it should be a separate issue)
> feat: Ability to @tag individuals in a post

- common.jsx
- src/DevGov/Notification/Item/Left.jsx
- src/DevGov/Notification/Item/Right.jsx
- src/gigs-board/components/boards/KanbanBoard.jsx
- src/gigs-board/components/layout/Controls.jsx
- src/gigs-board/components/layout/Navbar.jsx
- src/gigs-board/components/layout/Page.jsx
- src/gigs-board/components/layout/Search.jsx
- src/gigs-board/components/posts/CompactPost.jsx
- src/gigs-board/components/posts/List.jsx
- src/gigs-board/components/posts/Post.jsx
- src/gigs-board/components/posts/PostEditor.jsx
- src/gigs-board/components/teams/LabelsPermissions.jsx
- src/gigs-board/components/teams/TeamInfo.jsx
- src/gigs-board/pages/Boards.jsx
- src/gigs-board/pages/Feed.jsx
- src/gigs-board/pages/Post.jsx
- src/gigs-board/pages/Teams.jsx
Resolves #9 and #39.
Note, it was actually just a small change to the `common.jsx`, which was then applied to all the widgets with `npm run build`.
> fix: Propagate referral prop through all the components down to PostEditor labels

- src/gigs-board/components/layout/Controls.jsx
I preallocate the block height and width for the avatar, so it does not change its size after it is loaded. You could observe the top bar jumping after the avatar widget getting loaded. With this small fix, the parent `div` will have a const size, and thus the layout will not change its size over time.
> chore: Minor UI improvement to prevent page layout jumps

- src/gigs-board/components/layout/Page.jsx
Before the fix:
After this fix:
> hot fix z-index so liked person icons are beneath banner

- src/gigs-board/components/layout/Navbar.jsx
- src/gigs-board/components/posts/List.jsx
- src/gigs-board/components/posts/Search.jsx
Integrate @p516entropy and @Markeljan's work of hottest posts on navbar. Also make it works together with search, filter by labels/authors.
Preview:
https://near.social/#/bo.near/widget/gigs-board.pages.Feed?recency=hot&nearDevGovGigsContractAccountId=devgovgigs.near
> integrate hottest post on the navbar

- src/gigs-board/components/posts/List.jsx
- src/gigs-board/components/posts/PostEditor.jsx
Resolves https://github.com/near/devgigsboard-widgets/issues/10.
After this PR, labels that user does not have permission to add are hidden, when create and edit a post. Preview: https://near.social/#/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
And there is a warning if user without permission is trying to add such label:
Also, when user try to remove a label that he doesn't have a permission, it will now fail on UI and it will not be removed:
Previous to this PR it would not fail until submit the transaction:
Note that due to current near social viewer's limitation, it's not possible to add a lock icon to the protected labels like below, because related react-bootstrap-typeahead APIs are not exported:
> Hide labels that user does not have permission to add when create and edit

- src/gigs-board/components/posts/Post.jsx
Fix to showing the description section of a post collapsed when viewing the post page.
> Fix to showing Read More on post page #113

- .github/workflows/release.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
There are no changes to the DevHub components in this PR. I only updated the references and example commands from `near-social` to `bos` as it was renamed and further improved over time. If old `near-social` works for you, you can just keep using it. Newer `bos` CLI releases improved storage deposit management and added a couple of useful commands with more commands on the way.
> chore: migrate to bos CLI (formerly known as near-social CLI)

- communities.jsx
- src/gigs-board/components/community/CommunityHeader.jsx
- src/gigs-board/components/community/FeedHeader.jsx
- src/gigs-board/components/community/Layout.jsx
- src/gigs-board/pages/community/Events.jsx
- src/gigs-board/pages/community/Overview.jsx
- src/gigs-board/pages/community/Sponsorship.jsx
- src/gigs-board/pages/community/Telegram.jsx
Address #78. This uses the official telegram widget (iframe) to display individual message and I setup an aws lambda service to get the latest 10 message IDs from telegram groups: https://github.com/ailisp/cg-msg-counter/blob/main/index.js. There is no frontend-only solution to retrieve the message IDs.
Preview: https://near.social/#/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
Note that, due to #81 is not there, this PR uses hard coded telegram groups.
@ori-near ~I have trouble in layout these telegram messages in a beautiful way (they're iframes from https://t.me/`), may you take a look at the css here?~
There is no pure css way to make every iframe as height as the content. The JS way isn't work because near social VM prohibit direct access to …
> Community latest telegram messages

- src/DevGov/Notification/Item/Left.jsx
- src/DevGov/Notification/Item/Right.jsx
fixed issue [#110](https://github.com/near/neardevhub-widgets/issues/110) [Notifications] Rename notifications and Reposts to DevHub.
> fix: rename notifications

- src/gigs-board/components/layout/Page.jsx
Some elements may be cropped due to app layout height not being fixed.
Example:
With the given fix:
Page shown on the screenshots:
https://near.org/devgovgigs.near/widget/gigs-board.pages.Post?id=696
Fix preview:
https://near.org/root.akaia.near/widget/gigs-board.pages.Post?id=696&nearDevGovGigsContractAccountId=devgovgigs.near
> fix: Set minimum height for app layout

- src/gigs-board/pages/community/telegram.jsx
Address the Page improvement part of #157 
Make links work isn't possible due to VM limitation. I made a pull request there: https://github.com/NearSocial/VM/pull/92. Other than that, this PR and changes in https://github.com/ailisp/cg-msg-counter.git did:
-    Sort by newest first (since it's not intuitive and we want the views to refresh for users)
-   Add "Recent posts" Title
-   Add button to view more posts to take you to Telegram channel-
Preview: https://near.social/#/bo.near/widget/gigs-board.pages.community.telegram?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near
> Page improvements in community telegram page

- src/gigs-board/components/atom/button.jsx
- src/gigs-board/feature/github-integration/kanban-board-editor.jsx
Allows rendering buttons using \<a /\> as the root element.
```
{widget("components.atom.button", {
href: href("community.configure", { handle }),
label: "Configure community",
type: "link",
})}
```
Mainnet: https://near.org/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near
> Support buttons functioning as links

- module/core/lib/draftstate.js
- src/gigs-board/entity/post/List.jsx
- src/gigs-board/pages/Post.jsx
This fix will check the method name of the returned transaction and only show the post confirmation screen if it is edit_post or add_post. This means that for a `like`, it will just return to the feed, and not show any confirmation screen. Also the confirmation screen now shows that post is added or edited.
Preview URL: https://near.org/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.petersalomonsen.near
fixes #209
> fix: confirmation only for add/edit post

- playwright-tests/search.spec.js
- src/gigs-board/entity/post/List.jsx
- src/gigs-board/feature/post-search/panel.jsx
Implement https://github.com/near/neardevhub-widgets/issues/115. Fix #292 #248 #106
The search code is in QueryAPI, code is public here: https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bo.near/devhub_v17&view=editor-window can be forked and updated if there's update in post add / edit format.
https://near.social/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
search one of author, tag or content; search author + tag, author + content, tag + content; search author + tag + content. All testing produce correct result.
- A design for search result pagination is needed to have that pagination on the UI. It currently hard coded to display top 100 search result, to make server response faster enough. In practice, it's not a problem …
> Implement server side search

- src/devhub/feature/post-search/panel.jsx
Sort on new app https://near.social/devgovgigs.near/widget/app?page=feed is broken. This PR fix it.
@elliotBraem  How to preview the new app on mainnet, with widgets from bo.near but devgovgigs.near contract?
Previously I have: https://near.social/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
but this doesn't work: https://near.social/bo.near/widget/app?nearDevGovGigsContractAccountId=devgovgigs.near&page=feed
> Fix sort on new app

- src/devhub/components/island/connect.jsx
- src/devhub/components/island/participate.jsx
- src/devhub/page/contribute.jsx
- Fixed typos. Changed Devhub to DevHub according to brand guidelines.
- Fixed numbering of actions on participate section.
> Fix: Typos and numbering in participate section

- src/devhub/entity/addon/blog/Feed.jsx
- src/devhub/entity/addon/blog/editor/provider.jsx
- src/devhub/entity/post/List.jsx
Fix #248 
The main fixes are in query api side and our indexing logic, which is:
- https://github.com/near/near-databricks-lakehouse/commit/0e42f0d4862a079e89becd3f3df6e977f648f4b7 which fixes contract filter logic, found about 15 missing posts. The one reported by @elliotBraem is one these posts.
- https://github.com/ailisp/devhub-queryapi/commit/63c91e34d07dd19fcd55620e163632e4d7c979c0 which fixes the handling posts created by FastAuth accounts. For example, https://near.social/devhub.near/widget/app?page=post&id=1691 from production, you cannot find it in production but it can be found after this fix.
The first around 60 posts are more challenging than the later ones, because they are not created by `add_post` and not stored in the `posts` vector in the contract and from a old version …
> fix missing posts for post_id > 60

- src/devhub/entity/post/Post.jsx
Resolved https://github.com/near/neardevhub-widgets/issues/311
Proposed changes include:
- Show Collapse Replies + change arrow direction to let user know replies are open
- Hide expand replies option when there are no replies
- Added bottom margin to replies to separate replies
> Expanded posts replies shows visual indicator to close replies

- src/devhub/entity/addon/blog/Feed.jsx
- src/devhub/entity/addon/blog/editor/provider.jsx
- src/devhub/entity/post/List.jsx
devhub_v36 indexer includes old post ids < 60 by running a script after deployment. It also should include new posts. Since https://github.com/near/queryapi/issues/407, the older indexers stop pick up new blocks but the newest indexer works just fine
> use v36 indexer which include old posts id < 60

- src/devhub/entity/addon/blog/Feed.jsx
- src/devhub/entity/post/List.jsx
Old posts (id < 60) from state dump don't have a block height but all posts have timestamp, sort by timestamp fix the ordering
> fix ordering

- playwright-tests/tests/feed.spec.js
- src/devhub/entity/post/List.jsx
Resolved https://github.com/near/neardevhub-widgets/issues/479
The posts with tag "devhub-test" are hidden from the feed by default, but they can be viewed when searching for "devhub-test" tag
> Hide posts with "devhub-test" tag from feed

- src/devhub/components/molecule/SimpleMDE.jsx
- src/devhub/page/create.jsx
> Fix tagging

- src/devhub/entity/community/Activity.jsx
Resolved https://github.com/near/neardevhub-widgets/issues/529
> Community Activity takes full space on desktop when no posts

- src/devhub/entity/post/Post.jsx
- src/devhub/entity/post/PostEditor.jsx
Resolved https://github.com/near/neardevhub-widgets/issues/469
The cause of this issue was due to the props not being saved with post. The props being passed to the editor didn't exist. So I wrote some regex to extract those props from the description and used them.
For future posts, I recommend saving these props when creating the post.
https://github.com/near/neardevhub-widgets/assets/46527178/2f671f26-4771-42eb-bed5-5066a5b54425
> Add sponsorship information in post editor

- src/devhub/entity/addon/blog/editor/provider.jsx
- src/devhub/entity/post/Post.jsx
- src/devhub/entity/post/PostEditor.jsx
- src/devhub/entity/team/LabelRow.jsx
- src/devhub/page/admin/index.jsx
- src/devhub/page/create.jsx
_Resolves #549_
This removes the deposit from all function calls to DevHub contract in our codebase, and set the gas for all of them to `Big(10).pow(14)` ([MAX_GAS](https://github.com/near/near-api-js/blob/858b8ee35ffc7d6409b3d72b01f59f4e117db613/packages/cookbook/utils/calculate-gas.js#L10))
> Removes deposit and reduces gas

- src/devhub/entity/addon/blog/editor/provider.jsx
- src/devhub/entity/post/Post.jsx
- src/devhub/entity/post/PostEditor.jsx
- src/devhub/entity/team/LabelRow.jsx
- src/devhub/page/admin/index.jsx
- src/devhub/page/create.jsx
Resolves https://github.com/near/neardevhub-widgets/issues/549
This removes the deposit from all function calls to DevHub contract in our codebase, and set the gas for all of them to Big(10).pow(14) ([MAX_GAS](https://github.com/near/near-api-js/blob/858b8ee35ffc7d6409b3d72b01f59f4e117db613/packages/cookbook/utils/calculate-gas.js#L10))
[PREVIEW](https://test.near.social/devhub-dev.testnet/widget/app)
> removes deposit and reduces gas (#551)

- src/devhub/components/molecule/AccountAutocomplete.jsx
- src/devhub/components/molecule/ProfileCard.jsx
- src/devhub/entity/community/Teams.jsx
- src/devhub/entity/community/configuration/AccessControlConfigurator.jsx
- src/devhub/page/community/configuration.jsx
Resolves #241 
Preview [link](https://near.social/megha19.near/widget/app?page=community.configuration&handle=devhub-test)
> Update admins input UI

- src/devhub/entity/post/Post.jsx
- src/devhub/entity/post/PostEditor.jsx
- src/devhub/page/create.jsx
Resolves #560 
Preview [link](https://near.org/megha19.near/widget/app?page=feed) 
For testing, please use an account which hasn't granted devgogigs account permission (for notifications)
I have tested: (using ref from [here](https://github.com/near/neardevhub-widgets/pull/552/files))
- add_post
- edit_post
- reply -> comment, idea, attestation, solution, sponsorship
- add_like
Let me know if there is anything missing
> Fix post-> deposit error

- src/devhub/entity/community/Announcements.jsx
> Enhance announcements UI

- .github/workflows/continuous-integration-workflow.yml
- playwright-tests/tests/funding.spec.js
- parse and stringify transaction text content to avoid flakyness caused by whitespace diff
- use `locator` instead of `selectAndAssert`
> fix(test): flaky solution/sponsorship tests

- playwright-tests/tests/addons.spec.js
- playwright-tests/tests/blog.spec.js
- playwright-tests/tests/bosloaderenvironment.spec.js
- playwright-tests/tests/communities.spec.js
- playwright-tests/tests/community.spec.js
- playwright-tests/tests/create.spec.js
- playwright-tests/tests/feed.spec.js
- playwright-tests/tests/search.spec.js
_Resolves #594_
**Blocked** 
The blog tests are configured with the addon deployed to [devgovgigs.near](https://near.org/devgovgigs.near/widget/devhub.entity.addon.blog.Configurator?handle=devhub-test)
They break when configured with the addon deployed to [devhub.near](https://near.org/devhub.near/widget/devhub.entity.addon.blog.Configurator?handle=devhub-test), as the blog selector does not show up.
> Points tests to devhub.near rather than devgovgigs.near

- .devcontainer/post-create.sh
- playwright-tests/storage-states/wallet-connected-peter.json
- playwright-tests/tests/addons.spec.js
- playwright-tests/tests/announcements.spec.js
- playwright-tests/tests/community.spec.js
- playwright-tests/tests/discussions.spec.js
- playwright.config.js
- scripts/build-preview.mjs
- src/devhub/entity/community/Discussions.jsx
Check the new discussion posted content with the post on SocialDB, and wait for it to match before reposting on discussions with `blockHeight`. This is to ensure that we don't repost the reference of a previous SocialDB post.
Preview URL: https://near.social/devhub.near/widget/app?page=community&handle=webassemblymusic&tab=discussions
Here's a video for one of the tests, when the content match, then the `create_discussion` confirmation dialog will show. The other test, where the content does not match, is just verifying that the dialog does not show after some seconds.
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/3b63b877-cb58-4939-96f7-dda8841abcdb
> fix(discussions): content match before repost on discussions

- playwright-tests/tests/discussions.spec.js
- src/devhub/entity/community/Discussions.jsx
Fix for discussions test that is not able to find the example transaction on mainnet RPC, by redirecting the request to archival RPC instead.
> test(discussions): redirect tx lookup to archival node

- src/devhub/entity/post/List.jsx
Resolves #684 
The issue was with scroll, since we made the position -> fixed to occupy whole page, I have made the feed part scrollable (else it will load all data together), ideally we should have pagination for it, but since we will move to proposals I didn't put much efforts, @ailisp let me know if I should work on pagination.
> Fix posts feed

- src/devhub/entity/addon/blog/Feed.jsx
- src/devhub/entity/addon/blog/editor/provider.jsx
- src/devhub/entity/post/List.jsx
Fix feed not loading for recent posts after Mar. 17 and recent blog post not showing up. Root cause is a query api bug that stopped the working indexer, and still under investigation of query api team. This fix address the problem for now, but if the bug is not fixed in query api side, future posts/blogs can still not loading in some indefinite future time
> fix indexer recently stopped due to queryapi bug

- playwright-tests/tests/community.spec.js
- playwright-tests/util/bos-loader.js
- src/devhub/entity/addon/github/Configurator.jsx
- src/devhub/page/addon.jsx
Preview link: https://near.org/devgovgigs.petersalomonsen.near/widget/app?page=community&handle=contract-standards&tab=github
---
This fix handles that the `kanbanBoards` incoming property is `null` or `undefined` and if there is no column object on the `parentState`.
Here's how it looks like in the test runner after the fix:
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/005fcf0c-79d1-44c2-a568-34a61d7e398a
Also note that in order to make preview environment work for community addons, the widget account received from the contract must be replaced with the preview environment account. This is implemented in https://github.com/NEAR-DevHub/neardevhub-bos/pull/704/files#diff-e7bf8855eb2ab74f245b0c5b0cfc1ea2fc83a3f0ee48b59ae54403e2b206bf43
fixes #703
> fix(community): error when opening github config

- playwright.config.js
- src/devhub/entity/proposal/Editor.jsx
- after the txn is approved for create/edit proposal, the updated proposal show appear, instead of create form
Preview [link](https://near.social/megha19.near/widget/app?page=create-proposal)
Note: the proposals feed won't work in preview since I have used `truedove38.near` for contract and the feed uses `devhub.near`
> Added updated proposal support for popup wallet

- playwright-tests/tests/addons.spec.js
- playwright-tests/tests/announcements.spec.js
- playwright-tests/tests/community.spec.js
- playwright-tests/tests/discussions.spec.js
- playwright-tests/util/addons.js
- scripts/migrate_tabs_addons.sh
- src/devhub/entity/community/Activity.jsx
- src/devhub/entity/community/configuration/AddonsConfigurator.jsx
- src/devhub/page/addon.jsx
- src/devhub/page/community/index.jsx
_Resolves #709_
_Resolves #587_
This PR removes the default tabs. First these things need to happen:
[Testnet preview](https://test.near.org/thomasguntenaar.testnet/widget/app?page=community&handle=test)
> Removing default tabs

- playwright-tests/storage-states/wallet-connected-with-devhub-moderator-access-key.json
- playwright-tests/tests/proposals.spec.js
- playwright-tests/util/rpcmock.js
- playwright-tests/util/transaction.js
- src/devhub/entity/proposal/CommentsAndLogs.jsx
- src/devhub/entity/proposal/Proposal.jsx
- add test case for approving a proposal with don't ask again enabled
- update log without having to refresh after saving changed timeline status
- confirmation toast when editing timeline update transaction is finished
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/f57b70d7-bdca-437b-a177-b27aefc54b44
fixes #800
> Edit proposal timeline with "don't ask again" enabled

- src/devhub/entity/proposal/Proposal.jsx
Resolves #813 
Note: It's already fixed for IC.
> Fix text overflow of linked proposals

- instances/devhub.near/widget/devhub/components/molecule/ShareLinkButton.jsx
- instances/devhub.near/widget/devhub/entity/proposal/Proposal.jsx
- playwright-tests/tests/proposal/proposals.spec.js
- scripts/dev-gateway.mjs
- scripts/rpc-cache-proxy.mjs
- add a share link button for copying url
- share proposal using the new share link button with a clean URL ( e.g. https://devhub.near.page/proposal/22 )
- add test for "Share to X" button
- Remove share to Email button
-  Get local widgets from bos loader via the local RPC proxy, so that there is no need to use a redirect-map with the VM anymore. Also since redirect maps does not works with "don't ask again", this approach eliminates the need for using `modifySocialNearGetRPCResponsesInsteadOfGettingWidgetsFromBOSLoader` in "don't ask again" tests ( since this is now moved to the RPC proxy ). 
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/55de1155-2029-4154-a8b8-56cbeb736b6a
fixes #851
> share link button for copying url, share proposal with clean URL

- instances/devhub.near/aliases.mainnet.json
- instances/devhub.near/widget/devhub/entity/proposal/CommentsAndLogs.jsx
- instances/devhub.near/widget/devhub/entity/proposal/Editor.jsx
- instances/devhub.near/widget/devhub/entity/proposal/Proposal.jsx
- instances/devhub.near/widget/devhub/entity/proposal/T&C.jsx
- instances/devhub.near/widget/devhub/entity/proposal/TermsAndConditions.jsx
- playwright-tests/tests/proposal/proposals.spec.js
- scripts/rpc-cache-proxy.mjs
> Update terms and condition

- instances/devhub.near/widget/devhub/entity/addon/blogv2/Card.jsx
- instances/devhub.near/widget/devhub/entity/addon/blogv2/Page.jsx
As @petersalomonsen mentioned [here](https://t.me/c/1822948693/1/6602). The tests flash a `VM is dead` message because of condionally styled components. 
This PR:
- Removed these conditions from the `styled` components and moved it into a class based on the category.
- Fixed the VM is dead flash.
- This should also improve the blogv2 test suite
> Remove conditional styled component from blogv2

- instances/devhub.near/widget/devhub/components/organism/Navbar.jsx
- instances/devhub.near/widget/devhub/entity/addon/blogv2/Viewer.jsx
- instances/devhub.near/widget/devhub/entity/addon/blogv2/editor/provider.jsx
- instances/devhub.near/widget/devhub/page/blogv2.jsx
This PR fixes the following:
- Ori pointed out that the blog link in the navigation bar still pointed to blog v1 instead of v2.
- Blogv2 page was still showing this `blog isn't configured yet` because no communityAddonId was being passed. 
- The provider referenced a function that wasn't defined in that file.
All these bugs are fixed with this PR.
> Show latest developer-dao blogs

- instances/devhub.near/widget/devhub/entity/addon/blogv2/editor/content.jsx
The submit button of the blog editor wasn't aligned on the right when a user created a new blog. Only when the blog already existed. 
Align the button on the right with flex (justify-between).
As you can see here it is now on the right again:
> Fixes bug: blog submit button alignment in UI

- .devcontainer/devcontainer.json
- .github/workflows/continuous-integration-workflow-events.yml
- instances/devhub.near/widget/devhub/page/community/index.jsx
- playwright-tests/testUtils.js
- playwright-tests/tests/community/sharelinks.spec.js
https://github.com/user-attachments/assets/9d2c1139-ebc5-46c2-8d8a-64985232ee76
fixes #889
> Clean URL for community share button, proposal link tests for events committee

- instances/devhub.near/widget/devhub/components/molecule/SimpleMDEViewer.jsx
- instances/infrastructure-committee.near/widget/components/admin/AboutConfigurator.jsx
- instances/infrastructure-committee.near/widget/components/pages/about.jsx
- playwright-tests/tests/infrastructure/infrastructure.near.spec.js
Added new markdown viewer since [simpleMDE](https://github.com/sparksuite/simplemde-markdown-editor?tab=readme-ov-file#how-it-works) uses [marked](https://github.com/markedjs/marked), so the editor and viewer now has the consistency.
> Added new markdown viewer for IC about page

- instances/devhub.near/widget/devhub/entity/addon/blogv2/editor/provider.jsx
As Joe pointed out submitting a blog with these characters: [ ] in the title does not work since they are not valid characters in the keys of the social contract. I made a small change to only allow numbers, capital and lowercase letters. Everything else is replace in the title by an empty string. That is done by this regex: `/[^a-z0-9A-Z]/g`
> Fix Bug: blog title won't submit with weird characters

- instances/devhub.near/widget/devhub/entity/proposal/Editor.jsx
- playwright-tests/tests/proposal/proposals.spec.js
- playwright-tests/util/cache.js
After submitting a proposal draft, all the proposal ids are fetched from the contract to check if a new was added. The problem is that NearSocialVM will cache the results of `get_all_proposals_ids` from the previous time that you submitted, and then when cache is invalidated, the first result will return a different number of proposal_ids in case someone submitted a proposal after the last time you did ( which is most often the case ).
To fix this issue, an additional check is added to check that the latest proposal title and description matches what you submitted. This way not only the number of proposal ids is enough to accept that the latest proposal id is the one you submitted, but also it must match the title and description.
This Pull Request adds a playwright test for the scenario, …
> fix(proposal): should show the proposal you submitted and not the previous

- instances/devhub.near/widget/devhub/entity/proposal/Editor.jsx
- instances/events-committee.near/widget/devhub/entity/proposal/Editor.jsx
- instances/infrastructure-committee.near/widget/components/proposals/Editor.jsx
- playwright-tests/tests/proposal/proposals.spec.js
Based on the report that some user only saw the submit button spinner keeping on spinning, which I assume is as reproduced in the test that can be seen in the video here:
https://github.com/user-attachments/assets/04d0e6f2-9d65-458e-95cd-729bce1173a4
The test reproduces a scenario where the transaction completes, but the view call for getting all proposal ids does not show the latest proposal immediately, which might happen in the case the transaction is not fully finalized. The previous implementation will then just keep on spinning, and so it is assumed that this is what the user experienced.
By retrying checking for the latest proposal until it matches the submitted title and description, the submitted proposal will be found eventually, and the submit button will stop spinning, and the …
> fix that submit draft keeps on spinning

- instances/devhub.near/widget/app.jsx
- instances/devhub.near/widget/devhub/entity/proposal/Proposal.jsx
- instances/devhub.near/widget/devhub/page/notfound.jsx
- instances/events-committee.near/widget/app.jsx
- instances/events-committee.near/widget/devhub/entity/proposal/Proposal.jsx
- instances/infrastructure-committee.near/widget/app.jsx
- instances/infrastructure-committee.near/widget/components/proposals/Proposal.jsx
- instances/infrastructure-committee.near/widget/components/rfps/Rfp.jsx
_Resolves [#970](https://github.com/NEAR-DevHub/neardevhub-bos/issues/970)_
> Add page not found banner

- instances/devhub.near/widget/devhub/components/organism/Navbar.jsx
- instances/events-committee.near/widget/devhub/components/organism/Navbar.jsx
- instances/infrastructure-committee.near/widget/components/proposals/Feed.jsx
- instances/infrastructure-committee.near/widget/components/proposals/Proposals.jsx
_Resolves #978_
Trentin asked for surfacing the approved proposals to the top. https://t.me/c/2066716446/6/829
This is a temporary solution since we will replace the queryAPI and thus also change how the feed works.
I split the feed component bc it only affects the feed infrastructure-committee and not the other portals.
This PR also fixes an error flash for events-commitee `hasModerator` is not a function.
I added to fetch 20 proposals on initial load so it actually shows approved proposals on top. See picture:
> Quick and dirty sorting for infra

- instances/devhub.near/widget/devhub/entity/proposal/VerificationStatus.jsx
- instances/events-committee.near/widget/devhub/entity/proposal/VerificationStatus.jsx
The [backend has been migrated](https://github.com/NEAR-DevHub/neardevhub-kyc-proxy/commit/3758c891a36261360a3e0d3de47e30d7064c9b66) to the new Shuttle infrastructure, so the URL has changed (the old URL is still active and runs the old version of the code).
The reported KYC status is now in SCREAMING_SNAKE_CASE and a new `EXPIRED` status is added.
I have also upgraded events-committee code (copied the whole component)
@race-of-sloths include
> feat: Added KYC expiration support
