src/DevGov/Notification/Item/Left.jsx
src/DevGov/Notification/Item/Right.jsx

fix: Fix near.social notification links

---

src/gigs-board/components/layout/Navbar.jsx

fix: Make Teams link open in current window

---

src/gigs-board/components/layout/Navbar.jsx
src/gigs-board/components/layout/Search.jsx
src/gigs-board/components/posts/PostEditor.jsx
src/gigs-board/pages/Feed.jsx

fix: Fixed search by tag

---

src/gigs-board/components/posts/List.jsx

fix: Fixed an error that quickly flashes on UI when label is selected

---

src/gigs-board/pages/Boards.jsx

feat: Sharing & refreshing boards - URL should represent the selected board

---

package-lock.json
src/gigs-board/components/layout/LikeButton/Faces.jsx
src/gigs-board/components/posts/Post.jsx

This PR will close #22 
Preview:

show accounts that liked a post in a dropdown

---

src/gigs-board/components/posts/Post.jsx
src/gigs-board/components/posts/PostEditor.jsx

Widgets tested in my fork. Fix #15

Batch grant notification permission with like/reply/edit if not granted before

---

src/gigs-board/pages/Boards.jsx

feat: Update the funding Kanban board to reflect funding stage gates

---

src/gigs-board/components/boards/KanbanBoard.jsx
src/gigs-board/pages/Boards.jsx

Addressing remaining comments in https://github.com/near/devgigsboard-widgets/issues/53#issuecomment-1472847115

feat: Use human-readable column titles on the Kanban board columns

---

src/gigs-board/components/layout/Page.jsx
src/gigs-board/pages/Boards.jsx

Implement https://github.com/near/devgigsboard-widgets/issues/56
preview:

add a main header to Gigs Board

---

src/gigs-board/components/community/CommunityHeader.jsx
src/gigs-board/components/community/Layout.jsx
src/gigs-board/components/layout/Banner.jsx
src/gigs-board/components/layout/Navbar.jsx
src/gigs-board/components/layout/Page.jsx
src/gigs-board/components/posts/List.jsx
src/gigs-board/components/posts/Post.jsx
src/gigs-board/components/posts/Search.jsx
src/gigs-board/pages/Feed.jsx

Modify to integrate the excellent work of fuzzy search made by @Markeljan into Gigs Board. Also allows to search result that both match search terms and with certain label. Close #66 
Preview:

Integrate fuzzy search 

---

src/gigs-board/components/layout/Navbar.jsx

add a circle icon to allow submit bug and feature requests

---

src/gigs-board/components/posts/Post.jsx

improve reply post UI experience

---

src/gigs-board/components/layout/Navbar.jsx
src/gigs-board/components/layout/SearchByAuthor.jsx
src/gigs-board/components/layout/SearchByLabel.jsx
src/gigs-board/components/posts/List.jsx
src/gigs-board/components/posts/Search.jsx

Can filter by author, label, and fuzzy search, or a combination of both/all of them.
Preview:
Example:

filter by author UI

---

CODEOWNERS

chore: Added CODEOWNERS

---

src/gigs-board/components/community/CommunityHeader.jsx
src/gigs-board/components/community/FeedHeader.jsx
src/gigs-board/components/layout/Banner.jsx
src/gigs-board/components/layout/Navbar.jsx

Resolves #75 and #103 
Preview: https://near.social/#/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near
Note that due to near social limitation, custom font cannot be used. I use closest font that [available in all browsers ](https://blog.hubspot.com/website/web-safe-html-css-fonts)

Landing page ux

---

src/gigs-board/components/community/CommunityHeader.jsx
src/gigs-board/components/community/FeedHeader.jsx
src/gigs-board/components/layout/Banner.jsx
src/gigs-board/components/posts/Post.jsx

Condense long post with read more

---

src/gigs-board/components/posts/Post.jsx

Fix #109 . Tested in safari, chrome, firefox. Preview: https://near.social/#/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

use js read more to work in all browsers

---

src/gigs-board/components/posts/PostEditor.jsx

Thanks @ori-near for flagging it.

fix: Fixed reply functionality

---

src/gigs-board/pages/Feed.jsx

As per @ori-near's request, we hard-code the featured communities for now on the front-end side.

Use fixed list of featured communities

---

src/gigs-board/entity/community/header.jsx
src/gigs-board/feature/community-editor/frame.jsx

Closes #169 
Mainnet: https://near.org/root.akaia.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

fix: Show telegram tab only when handle is non-zero string

---

src/gigs-board/feature/community-editor/frame.jsx

Community data sanitizing fix

---

src/gigs-board/pages/Feed.jsx

fixed [#170](https://github.com/near/neardevhub-widgets/issues/170)

fix: margin right and left to be equal

---

src/gigs-board/components/molecule/tile.jsx
src/gigs-board/entity/community/header.jsx
src/gigs-board/pages/community/teams.jsx

Resolves #133 . Sponsorship tab was already added by @near-akaia-root . This PR adds Teams tab.
Preview: https://near.social/#/bo.near/widget/gigs-board.pages.community.team?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near

Add community Teams tab

---

.github/workflows/continuous-integration-workflow.yml

Added CI workflow for prettier

feat: added CI workflow for prettier

---

src/gigs-board/entity/post/History.jsx
src/gigs-board/entity/post/List.jsx
src/gigs-board/entity/post/Post.jsx
src/gigs-board/pages/Post.jsx

**NOTE**: The preview URL below now contains the deployment of https://github.com/near/neardevhub-widgets/pull/197
I will change back to the contents of this PR once that other is completed.
Preview URL: https://near.org/devgovgigs.petersalomonsen.near/widget/gigs-board.pages.Post?id=8&timestamp=1688009948396559326&compareTimestamp=1688009918129563930
Based on the work here: https://near.social/#/markeljan.near/widget/PostWithHistory?id=268&timestamp=1682382435187494750&compareTimestamp=1677857800212765894&referral=
resolves #64

View post version history with differences

---

src/gigs-board/feature/community-editor/ui.jsx
src/gigs-board/pages/community/telegram.jsx

Preview: https://near.social/#/bo.near/widget/gigs-board.pages.community.telegram?handle=bo-com&nearDevGovGigsContractAccountId=devgovgigs.near
This addresses https://github.com/near/neardevhub-widgets/issues/157

allow multiple telegram

---

src/gigs-board/entity/post/PostEditor.jsx
src/gigs-board/pages/Create.jsx

Reverts near/neardevhub-widgets#205 to fix #210 #213

Revert "142 solution reply post"

---

src/gigs-board/entity/post/Post.jsx
src/gigs-board/entity/post/PostEditor.jsx
src/gigs-board/pages/Create.jsx

Makes changes to solution post form and sponsorship form to only allow USDT and NEAR.
_Resolves #198_

fix: only allows usdt or near for solution funding request #198

---

module/core/adapter/dev-hub.js
module/core/lib/gui/navigation.js
module/entity/viewer.js
module/include.js
src/gigs-board/components/atom/button.jsx
src/gigs-board/components/molecule/breadcrumbs.jsx
src/gigs-board/components/molecule/text-input.jsx
src/gigs-board/components/molecule/tile.jsx
src/gigs-board/components/organism/editor.jsx
src/gigs-board/entity/community/header.jsx
src/gigs-board/entity/post/List.jsx
src/gigs-board/entity/post/Post.jsx
src/gigs-board/entity/team-board/github-kanban.jsx
src/gigs-board/entity/team/LabelsPermissions.jsx
src/gigs-board/feature/community-editor/branding-section.jsx
src/gigs-board/feature/community-editor/ui.jsx
src/gigs-board/feature/github-integration/kanban-board-editor.jsx
src/gigs-board/feature/post-search/by-author.jsx
src/gigs-board/feature/post-search/by-tag.jsx
src/gigs-board/pages/Feed.jsx
src/gigs-board/pages/Teams.jsx
src/gigs-board/pages/communities.jsx
src/gigs-board/pages/community/activity.jsx
src/gigs-board/pages/community/sidebar.jsx
src/gigs-board/pages/community/sponsorship.jsx
src/gigs-board/pages/community/teams.jsx
src/gigs-board/pages/community/telegram.jsx
src/gigs-board/pages/community/wiki.jsx

(Mainnet)[https://near.social/carina.akaia.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near]

Add new DevHub methods and UI primitives & polish styles

---

src/gigs-board/components/atom/tag.jsx
src/gigs-board/components/molecule/tile.jsx
src/gigs-board/entity/community/sidebar.jsx
src/gigs-board/entity/post/Post.jsx
src/gigs-board/feature/github-integration/kanban-board-editor.jsx
src/gigs-board/pages/community/activity.jsx

Closes #235 
In addition, makes links for any zero-length 3rd party service handles hidden
[Mainnet](https://near.social/carina.akaia.near/widget/gigs-board.pages.community.activity?handle=near-discovery&nearDevGovGigsContractAccountId=devgovgigs.near)

Fix community sidebar issues

---

src/gigs-board/components/molecule/markdown-editor.jsx
src/gigs-board/components/molecule/markdown-viewer.jsx
src/gigs-board/components/organism/configurator.jsx
src/gigs-board/entity/community/sidebar.jsx
src/gigs-board/entity/post/CompactPost.jsx
src/gigs-board/entity/post/Post.jsx
src/gigs-board/entity/post/PostEditor.jsx
src/gigs-board/entity/team/TeamInfo.jsx
src/gigs-board/entity/workspace/post-ticket.jsx
src/gigs-board/pages/Create.jsx
src/gigs-board/pages/community/wiki.jsx

Makes changes to post form to feature a more powerful markdown editor
_Resolves https://github.com/near/neardevhub-widgets/issues/221_

feature: introduces better markdown functionality for posts #221

---

src/gigs-board/components/molecule/markdown-editor.jsx
src/gigs-board/components/molecule/markdown-viewer.jsx
src/gigs-board/components/organism/configurator.jsx
src/gigs-board/entity/community/sidebar.jsx
src/gigs-board/entity/post/CompactPost.jsx
src/gigs-board/entity/post/Post.jsx
src/gigs-board/entity/post/PostEditor.jsx
src/gigs-board/entity/team/TeamInfo.jsx
src/gigs-board/entity/workspace/post-ticket.jsx
src/gigs-board/pages/Create.jsx
src/gigs-board/pages/community/wiki.jsx

Resolves #256 
Also removes spell checking at @ori-near's request.

SimpleMDE Markdown Editor for posts

---

src/gigs-board/components/molecule/text-input.jsx
src/gigs-board/entity/community/configurator.jsx
src/gigs-board/entity/community/sidebar.jsx

Makes changes to the about form and sidebar
_Resolves #173_

Improve the About Form Fields and Sidebar Rendering

---

src/gigs-board/pages/community/teams.jsx

fix: removed moderators from team page

---

replacements.mainnet.json

fix: adds replacements for mainnet

---

playwright-tests/search.spec.js
src/gigs-board/entity/post/List.jsx
src/gigs-board/feature/post-search/by-author.jsx
src/gigs-board/feature/post-search/by-tag.jsx
src/gigs-board/feature/post-search/panel.jsx
src/gigs-board/pages/Feed.jsx

- remove the search button, instead press enter to search
- after click an author or label instantly trigger the search
- keep screen not scrolling when doing a search
Preview: https://near.social/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

Improve search ux

---

docs/how-we-work.md

add a section about testing to the how-we-work document

docs(how-we-work): implementing tests

---

src/devhub/entity/post/PostEditor.jsx
src/devhub/page/create.jsx
src/gigs-board/entity/post/PostEditor.jsx
src/gigs-board/pages/Create.jsx

Fix #365 
Preview: 
https://near.social/bo.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near

Update default supervisor to neardevdao.near

---

src/devhub/components/island/participate.jsx
src/devhub/components/organism/Navbar.jsx
src/devhub/feature/post-search/panel.jsx
src/devhub/page/about.jsx
src/devhub/page/communities.jsx
src/devhub/page/contribute.jsx

Made minor design changes and added URLs for some links for the new homepage revamp.

Minor design fixes to new homepage

---

src/devhub/components/molecule/Select.jsx
src/devhub/entity/addon/wiki/Configurator.jsx
src/devhub/entity/addon/wiki/Viewer.jsx
src/devhub/entity/community/configuration/AddonsConfigurator.jsx
src/devhub/page/community/configuration.jsx

__Resolves #381 __
[Preview](https://near.org/devgovgigs.near/widget/app?page=community&handle=devhub-test)

Fixes legibility issues for community configuration page and fixes the Wiki viewer

---

src/devhub/entity/addon/wiki/Viewer.jsx

A merge conflict must've messed this up before. Fixing as it should be.

fix: ability to view the widget page

---

src/devhub/components/organism/NewsLetter.jsx

fix: Updated the social media links

---

src/app.jsx
src/devhub/entity/post/List.jsx
src/devhub/entity/post/Post.jsx
src/devhub/page/post.jsx

fix: create a post page

---

src/devhub/components/island/participate.jsx
src/devhub/components/molecule/ProfileCard.jsx
src/devhub/components/organism/Navbar.jsx

Fix Initial Homepage issues

---

src/devhub/components/molecule/ProfileCard.jsx
src/devhub/entity/community/Activity.jsx
src/devhub/entity/post/List.jsx
src/devhub/entity/post/Post.jsx
src/devhub/feature/post-search/panel.jsx
src/devhub/page/community/index.jsx

https://github.com/near/neardevhub-widgets/issues/405

Responsive Posts + Fix some issues

---

src/devhub/components/island/participate.jsx
src/devhub/components/molecule/NavbarDropdown.jsx
src/devhub/components/organism/Navbar.jsx
src/devhub/page/contribute.jsx

- Added Participate section activities and links.
- Added copy on contribute page
- Added links to navbar dropdown menu "About". Only blog link pending in the navbar.

Improved participate section, page and navbar links.

---

src/devhub/components/island/banner.jsx
src/devhub/components/island/hero.jsx
src/devhub/components/organism/Navbar.jsx
src/devhub/components/organism/NewsLetter.jsx
src/devhub/entity/community/Activity.jsx
src/devhub/page/post.jsx

- Update Banner for Mobile
- Update Hero section for Mobile
- Update Navbar for Mobile
- Update Newsletter for Mobile
- Fix Community Activity width
- Fix padding in post page

Mobile UI Improvements

---

src/devhub/components/organism/Configurator.jsx

Solves the issue of community configurations breaking

fix: reverts change to new Configurator

---

package-lock.json
package.json
playwright-tests/storage-states/wallet-connected.json
playwright-tests/storage-states/wallet-not-connected.json
playwright-tests/testUtils.js
playwright-tests/tests/communities.spec.js
playwright-tests/tests/community.spec.js
playwright.config.js
scripts/dev-gateway.mjs

gateway for local development and running tests without having to handle cookie consent or terms of use acceptance
fixes #459

feat: dev and test gateway

---

.gitignore
playwright-tests/tests/feed.spec.js
src/devhub/entity/post/Post.jsx
src/devhub/entity/post/PostEditor.jsx
src/devhub/feature/post-search/panel.jsx
src/devhub/page/feed.jsx

Resolves https://github.com/near/neardevhub-widgets/issues/454

Add Cancel button for post editor

---

src/devhub/entity/addon/blog/Feed.jsx
src/devhub/entity/addon/blog/editor/provider.jsx
src/devhub/entity/post/List.jsx

_Resolves #465_
Uses v32 query api rather than v34

fix: Use v34 query api

---

src/devhub/components/molecule/MarkdownEditor.jsx
src/devhub/components/molecule/SimpleMDE.jsx

Resolved https://github.com/near/neardevhub-widgets/issues/469

Post editor uses original fields

---

src/devhub/entity/addon/blog/Feed.jsx
src/devhub/entity/addon/blog/editor/provider.jsx
src/devhub/entity/post/List.jsx

fix: updates indexer to v35

---

src/devhub/components/molecule/ProfileCard.jsx

Fix profile navigation

---

src/devhub/components/molecule/AccountAutocomplete.jsx
src/devhub/entity/post/PostEditor.jsx
src/devhub/page/create.jsx

Ft: Autocomplete widget added

---

src/devhub/entity/post/Post.jsx

Fix filter tag action

---

src/devhub/entity/post/Post.jsx
src/devhub/entity/post/PostEditor.jsx
src/devhub/page/create.jsx

Resolves https://github.com/near/neardevhub-widgets/issues/482
Changes:
- Tabbed UI for Post Creator
- Tabbed UI for Post Editor

UX: Consistent Posts Preview UI

---

src/devhub/entity/community/Card.jsx
src/devhub/page/communities.jsx

Resolved https://github.com/near/neardevhub-widgets/issues/481
https://github.com/near/neardevhub-widgets/assets/46527178/c0b0f499-4e4e-43f8-a5c3-c916b8e503a8

Community page changes

---

.all-contributorsrc
CONTRIBUTING.md
README.md

add contributors file

---

src/devhub/page/post.jsx

Fix overflow of pages like this on mobile
https://near.org/devgovgigs.near/widget/app?page=post&id=2337

Fix posts width on mobile

---

src/devhub/entity/post/List.jsx
src/devhub/entity/post/Post.jsx
src/devhub/feature/post-search/panel.jsx

Resolves #429 
Preview [link](https://near.social/dev.near/widget/app?page=feed)

Fix tag action

---

src/devhub/entity/post/PostEditor.jsx
src/devhub/page/create.jsx

Fix reply-> description tagging

---

CODEOWNERS

Adding @elliotBraem and me as code owners

Add elliot and thomas to CODEOWNERS

---

playwright-tests/tests/community.spec.js
src/devhub/entity/addon/telegram/Viewer.jsx
src/devhub/page/community/index.jsx
src/devhub/page/create.jsx

Resolves #544 
Preview [link](https://near.org/megha19.near/widget/app?page=communities)
@elliotBraem @ailisp I have updated the breaking UI part.
and the handle and URL issue.
Please let me know what update should be there in configurations section 
what I understand is we have two telegram configurations: 
1) About section -> `telegram_handle` : which is string and singular
2) Addons -> telegram: which is array and can have multiple handles
cc: @Tguntenaar

Fix telegram string and array issue

---

src/devhub/entity/post/List.jsx
src/devhub/entity/post/Post.jsx
src/devhub/entity/post/PostEditor.jsx
src/devhub/entity/post/draft.jsx

Clear draft changes after txn is approved

---

src/devhub/entity/post/Post.jsx

Fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/227
Preview https://near.org/itexpert120-contra.near/widget/app?page=feed

Make "See more" button more visible

---

src/devhub/components/molecule/BadgeDetails.jsx
src/devhub/components/molecule/MarkdownViewer.jsx
src/devhub/components/molecule/ProfileCard.jsx
src/devhub/components/molecule/ProfileLine.jsx
src/devhub/entity/community/Teams.jsx
src/devhub/entity/post/Post.jsx
src/devhub/page/admin/moderatorsTab.jsx

Migrates neardevgov to devhub

---

src/devhub/components/molecule/CommunityControl.jsx
src/devhub/feature/post-search/panel.jsx
src/devhub/page/communities.jsx

Resolved https://github.com/NEAR-DevHub/neardevhub-bos/issues/611
Preview
- Communities: https://near.social/itexpert120-contra.near/widget/app?page=communities
- Feed: https://near.social/itexpert120-contra.near/widget/app?page=feed

Consistent page controls in Feed and Communities page

---

src/devhub/page/create.jsx

Fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/596
Fixes https://github.com/NEAR-DevHub/neardevhub-bos/issues/501
Preview https://near.org/itexpert120-contra.near/widget/app?page=create
- Added Submit button on Preview page
- Many UI enhancements, including better mobile UI and disabled submit button when there is no title and description

Create Page Enhancements

---

replacements.dev.json
replacements.mainnet.json
replacements.testnet.json
src/core/lib/common.jsx
src/devhub/entity/post/Post.jsx
src/devhub/entity/post/PostEditor.jsx

Resolves #629 
Preview [link](https://near.org/megha19.near/widget/app?page=create)

Fix no storage -> deposit issue

---

CONTRIBUTING.md
playwright-tests/storage-states/wallet-connected-community-admin.json
playwright-tests/tests/communities.spec.js
playwright-tests/tests/community.spec.js

added docs for the dev container setup with instructions on how to start the test environment from within it
added test for create and edit community
part of implementing #593

Regression test cases

---

playwright-tests/tests/announcements.spec.js
playwright-tests/tests/community.spec.js
src/devhub/components/organism/Feed.jsx
src/devhub/components/organism/Feed/NearQueryApi.jsx
src/devhub/entity/community/Announcements.jsx
src/devhub/entity/community/Compose.jsx

Announcements tests

---

CODEOWNERS

Update CODEOWNERS to include Megha

---

src/core/adapter/devhub-contract.jsx

updated price on the tx

---

src/core/adapter/devhub-contract.jsx

Fix community create txn error of insufficient gas

---

src/devhub/components/organism/NewsLetter.jsx
src/devhub/components/templates/AppLayout.jsx
src/devhub/entity/community/Teams.jsx
src/devhub/page/community/index.jsx

Preview [link](https://near.social/megha19.near/widget/app?page=feed)

Make website occupy full screen width and Footer UI update

---

src/devhub/entity/post/PostEditor.jsx

Resolves #676 
Preview [link](https://near.org/megha19.near/widget/app?page=create)

Fix post editor page bug

---

src/devhub/entity/addon/blog/Page.jsx
src/devhub/entity/addon/kanban/Configurator.jsx
src/devhub/entity/post/List.jsx
src/devhub/entity/proposal/Proposal.jsx

Fix only limited posts feed

---

playwright-tests/storage-states/wallet-connected-chain-abstraction-community-admin.json
playwright-tests/tests/community.spec.js
playwright.config.js
src/devhub/components/organism/Configurator.jsx

https://near.social/devgovgigs.petersalomonsen.near/widget/app?page=communities
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/1486222f-133a-4add-a1df-887c0eb97aad
https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/ef9c5475-3ea2-4c18-a1a3-de5429975917
fixes #698

fix(community): unable to edit about section of community

---

src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/Editor.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/Proposal.jsx
src/devhub/entity/proposal/StatusTag.jsx

Preview [link](https://near.org/megha19.near/widget/app?page=proposals)

Fixed critical proposal bugs

---

src/devhub/entity/proposal/Feed.jsx

Preview [link](https://near.org/megha19.near/widget/app?page=proposals)

Feed page UI updated

---

src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/ComposeComment.jsx
src/devhub/entity/proposal/Editor.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/Proposal.jsx
src/devhub/entity/proposal/StatusTag.jsx
src/devhub/entity/proposal/VerificationStatus.jsx

Fix proposals timeline modal

---

playwright-tests/testUtils.js
playwright-tests/tests/community.spec.js
playwright-tests/tests/create.spec.js
playwright-tests/tests/feed.spec.js
playwright-tests/tests/proposals.spec.js
src/devhub/entity/proposal/ComposeComment.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/LikeButton.jsx
src/devhub/entity/proposal/Proposal.jsx

Resolves #726 
Resolves #727 
Resolves #728 
- added likes by user on hover 
Preview [link](https://near.org/megha19.near/widget/app?page=proposals)

Moderator UX Improvements

---

src/devhub/entity/proposal/Proposal.jsx
src/devhub/entity/proposal/VerificationStatus.jsx

Preview [link](https://near.org/megha19.near/widget/app?page=proposasl)

Fix proposal timestamp and KYC dropdown action

---

playwright-tests/tests/activity-feed.spec.js
src/devhub/components/feed/MergedIndexFeed.jsx
src/devhub/components/feed/SubscribedFeed.jsx
src/devhub/components/templates/AppLayout.jsx
src/devhub/page/announcements.jsx

_Resolves #737_
[Preview](https://near.org/thomasguntenaar.near/widget/app?page=announcements)

View feed as community.devhub.near as anonymous user

---

src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/Profile.jsx
src/devhub/entity/proposal/Proposal.jsx

- added feed search by proposal id
- made all profile links clickable
- updated timeline to show approved when status is funded or payment processing
Preview [link](https://near.org/megha19.near/widget/app?page=proposals)

Proposals UI enhancements

---

src/core/adapter/devhub-contract.jsx
src/devhub/page/admin/index.jsx

Preview [link](https://near.org/megha19.near/widget/app?page=admin)

Moved from `devgovgigs` to `devhub` contract for admin configuration

---

src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/LikeButton.jsx
src/devhub/entity/proposal/Proposal.jsx

- Added likes by user on hover for comments
- Fixed squeezed radio button on near.social
- Hide linked proposals when it's 0
Preview [link](https://near.social/megha19.near/widget/app?page=proposals)

Proposal UI enhancements

---

playwright-tests/tests/proposals.spec.js
src/devhub/components/molecule/Compose.jsx
src/devhub/components/molecule/SimpleMDE.jsx
src/devhub/entity/proposal/ComposeComment.jsx
src/devhub/entity/proposal/Editor.jsx

Resolves #710 
Preview [link](https://near.org/megha19.near/widget/app?page=create-proposal)

Auto reference existing proposal

---

src/devhub/entity/proposal/Editor.jsx
src/devhub/entity/proposal/Proposal.jsx

Fix timeline update after user updates proposal status 

---

src/app.jsx
src/devhub/components/templates/AppLayout.jsx

Resolves #782 
Resolves [#1163](https://github.com/near/near-discovery/issues/1163)
https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/ddba5763-77dc-4121-a8ef-ac3c7f1c6c7b

Removed top level fixed positioning

---

src/devhub/entity/proposal/CommentsAndLogs.jsx

Resolves #785 
Note: this problem is specific to devhub proposals instance only.

Remove proposal version log

---

.github/ISSUE_TEMPLATE/bug_report.md
playwright-tests/tests/proposals.spec.js
playwright-tests/util/cache.js
src/devhub/components/molecule/Compose.jsx
src/devhub/components/molecule/SimpleMDE.jsx
src/devhub/components/templates/AppLayout.jsx
src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/ComposeComment.jsx
src/devhub/entity/proposal/Editor.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/Proposal.jsx
src/devhub/feature/proposal-search/by-author.jsx
src/devhub/feature/proposal-search/by-category.jsx
src/devhub/feature/proposal-search/by-sort.jsx
src/devhub/feature/proposal-search/by-stage.jsx

Fix feed filter, compose comment, dropdown visibility for events committee

---

src/devhub/components/molecule/SimpleMDE.jsx
src/devhub/entity/proposal/CommentsAndLogs.jsx
src/devhub/entity/proposal/Feed.jsx
src/devhub/entity/proposal/LinkedProposalsDropdown.jsx

@Tguntenaar can you please also check the indexer for events-committee

Update indexer query

---

src/devhub/entity/proposal/Editor.jsx

feat: single click ready for review

---

playwright-tests/tests/proposals.spec.js
src/devhub/components/molecule/Input.jsx

Resolves #790 
https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/b19e832d-4d20-46b1-bc55-688d83b93bde

Add formatting to Amount Field

---

playwright-tests/tests/other/admin.spec.js
src/devhub/entity/proposal/AccountInput.jsx
src/devhub/page/admin/AccountsEditor.jsx
src/devhub/page/admin/moderatorsTab.jsx

Add account autocomplete to moderators tab

---

src/devhub/entity/proposal/VerificationStatus.jsx

Resolves #810 
This will fix it for devhub and IC

Fix fractal status when API is down

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/deploy-dev-testnet.yml
.github/workflows/deploy-prod-mainnet.yml
.github/workflows/promote-develop-to-main.yml

feat: migrate to actions/checkout@v4

---

instances/devhub.near/widget/devhub/entity/proposal/Feed.jsx
playwright-tests/tests/proposal/proposals.spec.js
scripts/rpc-cache-proxy.mjs

Resolves #855 
https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/662458a4-ff73-4bdd-9ef1-683705357bfb

Added load more instead of infinite scroll to proposal feed

---

instances/devhub.near/widget/devhub/components/molecule/Button.jsx
instances/devhub.near/widget/devhub/entity/proposal/CommentsAndLogs.jsx
instances/devhub.near/widget/devhub/entity/proposal/Proposal.jsx
playwright-tests/tests/proposal/proposals.spec.js
playwright-tests/util/transaction.js
scripts/rpc-cache-proxy.mjs

Move kyc from payment processing to review stage

---

instances/devhub.near/widget/devhub/entity/proposal/CommentsAndLogs.jsx
instances/devhub.near/widget/devhub/entity/proposal/Profile.jsx

Fix log vertical alignment

---

instances/devhub.near/widget/devhub/entity/proposal/CommentsAndLogs.jsx
instances/devhub.near/widget/devhub/entity/proposal/Editor.jsx
playwright-tests/tests/infrastructure/rfp.spec.js

Fix empty log

---

instances/infrastructure-committee.near/widget/components/molecule/LinkedProposalsDropdown.jsx
instances/infrastructure-committee.near/widget/components/molecule/LinkedRfpDropdown.jsx
instances/infrastructure-committee.near/widget/components/proposals/CommentsAndLogs.jsx
instances/infrastructure-committee.near/widget/components/proposals/Feed.jsx
instances/infrastructure-committee.near/widget/components/proposals/Proposal.jsx
instances/infrastructure-committee.near/widget/components/rfps/Feed.jsx
instances/infrastructure-committee.near/widget/components/rfps/Rfp.jsx

Fix `.then` issue with infra

---

instances/devhub.near/widget/devhub/entity/proposal/Proposal.jsx

923: Add updated instructions under DevHub Timeline Approved Stage

---

instances/devhub.near/widget/devhub/entity/proposal/VerificationStatus.jsx

- show loader until the status is fetched

Fix fractal verification display issue

---

instances/infrastructure-committee.near/widget/components/rfps/Editor.jsx

Error: https://nearblocks.io/txns/2ehpNgsXfPpfThgRdBRWzrfnGe1vpgaMWjKBe2CSTC2V#execution

Fix RFP timeline issue

---

instances/events-committee.near/widget/devhub/components/molecule/SimpleMDE.jsx
instances/infrastructure-committee.near/widget/components/molecule/SimpleMDE.jsx

I have just copied code from devhub to other instances for now, since Trentin is creating RFPs and would like to have image upload feature, but I created this #937 issue to reuse it later.

Add image uploader to events and infra

---

instances/devhub.near/widget/devhub/components/molecule/SimpleMDEViewer.jsx

Add css to table in markdown viewer

---

instances/devhub.near/widget/devhub/components/molecule/SimpleMDEViewer.jsx

Match iframe text style to that of outside frame

---

instances/infrastructure-committee.near/widget/components/proposals/Editor.jsx
playwright-tests/tests/infrastructure/proposal.spec.js

Resolves #946 
[video.webm](https://github.com/user-attachments/assets/d9db1f22-447e-4c92-8619-56a69ae50365)
[video.webm](https://github.com/user-attachments/assets/553fbab1-7acf-4a3a-99c7-39df3e3439da)

Should not add custom labels to proposal with linked RFPs

---

.devcontainer/devcontainer.json
instances/events-committee.near/widget/app.jsx
playwright-tests/tests/events/events.spec.js

Also changed to use node 20 in devcontainer setup ( because node 22 fails on compiling some of the dependencies ).
_Resolves #974_

Default page for events committee

---

instances/infrastructure-committee.near/widget/components/rfps/Rfp.jsx

_Resolves #979_
Small fix where we accidently queried the wrong GraphQL endpoint.

Fixed: getting approved proposals from queryAPI

---

instances/infrastructure-committee.near/widget/components/rfps/Editor.jsx
playwright-tests/tests/infrastructure/infrastructure.near.spec.js
playwright-tests/tests/infrastructure/rfp.spec.js

[video.webm](https://github.com/user-attachments/assets/39be59a4-93f4-45f5-bde8-de7446463322)
[video.webm](https://github.com/user-attachments/assets/1bd4778d-3d04-45b8-9888-5b2420d03470)

Fix view rfp after submit

---

instances/devhub.near/widget/devhub/components/molecule/SimpleMDEViewer.jsx
instances/devhub.near/widget/devhub/entity/proposal/CommentsAndLogs.jsx
instances/devhub.near/widget/devhub/entity/proposal/Profile.jsx
playwright-tests/tests/community/discussions.spec.js
playwright-tests/tests/other/admin.spec.js

Fix comments inline positioning

---

instances/devhub.near/widget/devhub/entity/proposal/VerificationStatus.jsx

Add toast to get kyc verification link
